In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_clean.csv')

In [3]:
state_str = '''Alabama 	01 	AL
Alaska 	02 	AK
Arizona 	04 	AZ
Arkansas 	05 	AR
California 	06 	CA
Colorado 	08 	CO
Connecticut 	09 	CT
Delaware 	10 	DE
District of Columbia 	11 	DC
Florida 	12 	FL
Georgia 	13 	GA
Hawaii 	15 	HI
Idaho 	16 	ID
Illinois 	17 	IL
Indiana 	18 	IN
Iowa 	19 	IA
Kansas 	20 	KS
Kentucky 	21 	KY
Louisiana 	22 	LA
Maine 	23 	ME
Maryland 	24 	MD
Massachusetts 	25 	MA
Michigan 	26 	MI
Minnesota 	27 	MN
Mississippi 	28 	MS
Missouri 	29 	MO
Montana 	30 	MT
Nebraska 	31 	NE
Nevada 	32 	NV
New Hampshire 	33 	NH
New Jersey 	34 	NJ
New Mexico 	35 	NM
New York 	36 	NY
North Carolina 	37 	NC
North Dakota 	38 	ND
Ohio 	39 	OH
Oklahoma 	40 	OK
Oregon 	41 	OR
Pennsylvania 	42 	PA
Rhode Island 	44 	RI
South Carolina 	45 	SC
South Dakota 	46 	SD
Tennessee 	47 	TN
Texas 	48 	TX
Utah 	49 	UT
Vermont 	50 	VT
Virginia 	51 	VA
Washington 	53 	WA
West Virginia 	54 	WV
Wisconsin 	55 	WI
Wyoming 	56 	WY'''

In [4]:
states = state_str.split('\n')

In [5]:
states = pd.DataFrame(list(map(lambda x: x.split('\t'),states)),columns=['state','id','Short'])

In [6]:
df = pd.merge(left=df,right=states,left_on='State',right_on='Short',how='right')

In [7]:
df.head()

,Unnamed: 0,Ticket ID,Ticket Created,Date of Issue,Time of Issue,Form,Method,Issue,Caller ID Number,Type of Call or Messge,...,State,Zip,Location,Issue DateTime,Offset,Issue DateTime UTC,Time Elapsed,state,id,Short
0,0,1000296,2016-05-25 11:15:29,05/01/2016,1:00pm,Phone,Internet (VOIP),Robocalls,866-410-0458,Autodialed Live Voice Call,...,FL,33324,"(26.131328, -80.264664)",2016-05-01 13:00:00,-14400.0,2016-05-24 17:00:00,23 days 18:15:29.000000000,Florida,12,FL
1,11,1000342,2016-05-25 13:32:27,05/24/2016,5:59pm,Phone,Wireless (cell phone/other mobile device),Telemarketing (including do not call and spoof...,281-808-2308,Live Voice,...,FL,33605,"(27.96128, -82.429811)",2016-05-24 17:59:00,-14400.0,2016-05-24 21:59:00,0 days 15:33:27.000000000,Florida,12,FL
2,15,1000374,2016-05-25 14:04:17,05/23/2016,3:01pm,Phone,Wired,Telemarketing (including do not call and spoof...,941-467-3194,Live Voice,...,FL,33952,"(26.992249, -82.096316)",2016-05-23 15:01:00,-14400.0,2016-05-24 19:01:00,1 days 19:03:17.000000000,Florida,12,FL
3,34,1000452,2016-05-25 14:53:50,05/23/2016,6:00pm,Phone,Wired,Telemarketing (including do not call and spoof...,305-823-2345,Live Voice,...,FL,33029,"(25.998658, -80.400741)",2016-05-23 18:00:00,-14400.0,2016-05-24 22:00:00,1 days 16:53:50.000000000,Florida,12,FL
4,39,1000466,2016-05-25 15:12:15,05/25/2016,10:00am,Phone,Wireless (cell phone/other mobile device),Telemarketing (including do not call and spoof...,NaN,Abandoned Calls,...,FL,33462,"(26.583366, -80.095478)",2016-05-25 10:00:00,-14400.0,2016-05-25 14:00:00,0 days 01:12:15.000000000,Florida,12,FL

In [8]:
state_counts = df.groupby(['id','state'])['Ticket ID'].count().reset_index().rename({'Ticket ID':'Count'},axis='columns')

In [12]:
state_counts.head()

    id        state  Count
0  01      Alabama    9131
1  02       Alaska    1015
2  04      Arizona   18367
3  05     Arkansas    4840
4  06   California   84542

In [24]:
item_counts = df.groupby(['id','state','Issue','Method','Type of Call or Messge'])['Ticket ID'].count()

In [25]:
item_counts = item_counts.reset_index()

In [26]:
item_counts.head()

,id,state,Issue,Method,Type of Call or Messge,Ticket ID
0,01,Alabama,Robocalls,Internet (VOIP),Abandoned Calls,10
1,01,Alabama,Robocalls,Internet (VOIP),Autodialed Live Voice Call,8
2,01,Alabama,Robocalls,Internet (VOIP),Prerecorded Voice,59
3,01,Alabama,Robocalls,Wired,Abandoned Calls,36
4,01,Alabama,Robocalls,Wired,Autodialed Live Voice Call,35

In [127]:
state_counts

     id                 state  Count
0   01                Alabama   9131
1   02                 Alaska   1015
2   04                Arizona  18367
3   05               Arkansas   4840
4   06             California  84542
5   08               Colorado  18961
6   09            Connecticut  10771
7   10               Delaware   2196
8   11   District of Columbia   3511
9   12                Florida  46801
10  13                Georgia  21505
11  15                 Hawaii   1999
12  16                  Idaho   3569
13  17               Illinois  25533
14  18                Indiana  10332
15  19                   Iowa   6761
16  20                 Kansas   5679
17  21               Kentucky   9500
18  22              Louisiana   6901
19  23                  Maine   2631
20  24               Maryland  19040
21  25          Massachusetts  16688
22  26               Michigan  18645
23  27              Minnesota  11843
24  28            Mississippi   3790
25  29               Missouri  10670
26  30                Montana   2242
27  31               Nebraska   4207
28  32                 Nevada   7770
29  33          New Hampshire   3108
30  34             New Jersey  21837
31  35             New Mexico   4201
32  36               New York  36976
33  37         North Carolina  21483
34  38           North Dakota   1074
35  39                   Ohio  25865
36  40               Oklahoma   7802
37  41                 Oregon  10434
38  42           Pennsylvania  28148
39  44           Rhode Island   1997
40  45         South Carolina   9288
41  46           South Dakota   1331
42  47              Tennessee  14309
43  48                  Texas  52520
44  49                   Utah   6387
45  50                Vermont   1157
46  51               Virginia  23413
47  53             Washington  19528
48  54          West Virginia   3178
49  55              Wisconsin  11443
50  56                Wyoming   1348

In [93]:
df.groupby(['state','id'])['Ticket ID'].count().sort_values()

state                  id
Alaska                 02      1015
North Dakota           38      1074
Vermont                50      1157
South Dakota           46      1331
Wyoming                56      1348
Rhode Island           44      1997
Hawaii                 15      1999
Delaware               10      2196
Montana                30      2242
Maine                  23      2631
New Hampshire          33      3108
West Virginia          54      3178
District of Columbia   11      3511
Idaho                  16      3569
Mississippi            28      3790
New Mexico             35      4201
Nebraska               31      4207
Arkansas               05      4840
Kansas                 20      5679
Utah                   49      6387
Iowa                   19      6761
Louisiana              22      6901
Nevada                 32      7770
Oklahoma               40      7802
Alabama                01      9131
South Carolina         45      9288
Kentucky               21      9500
Indiana                18     10332
Oregon                 41     10434
Missouri               29     10670
Connecticut            09     10771
Wisconsin              55     11443
Minnesota              27     11843
Tennessee              47     14309
Massachusetts          25     16688
Arizona                04     18367
Michigan               26     18645
Colorado               08     18961
Maryland               24     19040
Washington             53     19528
North Carolina         37     21483
Georgia                13     21505
New Jersey             34     21837
Virginia               51     23413
Illinois               17     25533
Ohio                   39     25865
Pennsylvania           42     28148
New York               36     36976
Florida                12     46801
Texas                  48     52520
California             06     84542
Name: Ticket ID, dtype: int64

In [58]:
import json

with open('viz/us.json','r') as f:
    j =json.load(f)

In [75]:
[el['id'] for el in j['objects']['states']['geometries']]

['05',
 '06',
 '17',
 '20',
 '28',
 '39',
 '48',
 '01',
 '19',
 '22',
 '27',
 '29',
 '31',
 '04',
 '08',
 '18',
 '26',
 '30',
 '36',
 '41',
 '51',
 '56',
 '37',
 '40',
 '47',
 '55',
 '02',
 '50',
 '38',
 '13',
 '23',
 '44',
 '54',
 '16',
 '46',
 '35',
 '53',
 '42',
 '12',
 '49',
 '21',
 '33',
 '45',
 '32',
 '15',
 '34',
 '09',
 '24',
 '25',
 '10',
 '11']

In [16]:
states_data = pd.read_html('https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population')

In [17]:
state_data = states_data[0]

In [18]:
state_data.columns = state_data.iloc[0,:]

In [19]:
state_data = state_data.iloc[1:,:]

In [20]:
state_data = state_data.iloc[:,2:4]

In [21]:
state_data.columns = ['State_Name','Pop']

In [128]:
df_all = pd.merge(state_counts,state_data,left_on='state',right_on='State_Name',how='inner')

In [129]:
df['state'] = df['state'].apply(lambda x: x.strip())

In [135]:
df_all['Pop'].astype('int')/100000

0      48.87871
1       7.37438
2      71.71646
3      30.13825
4     395.57991
5      56.95564
6      35.72665
7       9.67171
8       7.02455
9     212.99325
10    105.19475
11     14.20491
12     17.54208
13    127.41080
14     66.91878
15     31.56145
16     29.11505
17     44.68402
18     46.59978
19     13.38404
20     60.42718
21     69.02149
22     99.95915
23     56.11179
24     29.86530
25     61.26452
26     10.62305
27     19.29268
28     30.34392
29     13.56458
30     89.08520
31     20.95428
32    195.42209
33    103.83620
34      7.60077
35    116.89442
36     39.43079
37     41.90713
38    128.07060
39     10.57315
40     50.84127
41      8.82235
42     67.70010
43    287.01845
44     31.61105
45      6.26299
46     85.17685
47     75.35591
48     18.05832
49     58.13568
50      5.77737
Name: Pop, dtype: float64

In [136]:
df_df_all['Count']/df_all['Pop'].astype('int')*100000

0     186.809349
1     137.638690
2     256.105781
3     160.593266
4     213.716617
5     332.908207
6     301.483626
7     227.053954
8     499.818494
9     219.729968
10    204.430354
11    140.725988
12    203.453638
13    200.399024
14    154.396120
15    214.217027
16    195.053761
17    212.603969
18    148.090828
19    196.577416
20    315.089998
21    241.779770
22    186.526196
23    211.060813
24    126.903128
25    174.162794
26    211.050499
27    218.061980
28    256.064477
29    229.126151
30    245.124892
31    200.484102
32    189.210954
33    206.893164
34    141.301473
35    221.268047
36    197.865678
37    248.979112
38    219.785025
39    188.874649
40    182.686231
41    150.866833
42    211.358624
43    182.984752
44    202.049600
45    184.736045
46    274.875157
47    259.143576
48    175.985363
49    196.832651
50    233.324160
dtype: float64

In [27]:
item_counts = item_counts.rename({'Type of Call or Messge':'type','Ticket ID':'count','Issue':'issue','Method':'method'},axis='columns')

In [28]:
item_counts = item_counts.applymap(lambda x: str(x).strip())

In [29]:
item_counts

,id,state,issue,method,type,count
0,01,Alabama,Robocalls,Internet (VOIP),Abandoned Calls,10
1,01,Alabama,Robocalls,Internet (VOIP),Autodialed Live Voice Call,8
2,01,Alabama,Robocalls,Internet (VOIP),Prerecorded Voice,59
3,01,Alabama,Robocalls,Wired,Abandoned Calls,36
4,01,Alabama,Robocalls,Wired,Autodialed Live Voice Call,35
5,01,Alabama,Robocalls,Wired,Prerecorded Voice,310
6,01,Alabama,Robocalls,Wireless (cell phone/other mobile device),Abandoned Calls,47
7,01,Alabama,Robocalls,Wireless (cell phone/other mobile device),Autodialed Live Voice Call,55
8,01,Alabama,Robocalls,Wireless (cell phone/other mobile device),Prerecorded Voice,476
9,01,Alabama,Robocalls,Wireless (cell phone/other mobile device),Text Message,11
10,01,Alabama,Telemarketing (including do not call and spoof...,Internet (VOIP),Abandoned Calls,34
11,01,Alabama,Telemarketing (including do not call and spoof...,Internet (VOIP),Live Voice,86
12,01,Alabama,Telemarketing (including do not call and spoof...,Internet (VOIP),Prerecorded Voice,85
13,01,Alabama,Telemarketing (including do not call and spoof...,Wired,Abandoned Calls,204
14,01,Alabama,Telemarketing (including do not call and spoof...,Wired,Email,2
15,01,Alabama,Telemarketing (including do not call and spoof...,Wired,Live Voice,564
16,01,Alabama,Telemarketing (including do not call and spoof...,Wired,Prerecorded Voice,350
17,01,Alabama,Telemarketing (including do not call and spoof...,Wired,Text Message,2
18,01,Alabama,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Abandoned Calls,95
19,01,Alabama,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Email,6
20,01,Alabama,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Live Voice,645
21,01,Alabama,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Prerecorded Voice,484
22,01,Alabama,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Text Message,87
23,01,Alabama,Unwanted Calls,Internet (VOIP),Abandoned Calls,121
24,01,Alabama,Unwanted Calls,Internet (VOIP),Live Voice,73
25,01,Alabama,Unwanted Calls,Internet (VOIP),Prerecorded Voice,136
26,01,Alabama,Unwanted Calls,Internet (VOIP),Text Message,2
27,01,Alabama,Unwanted Calls,Wired,Abandoned Calls,282
28,01,Alabama,Unwanted Calls,Wired,Live Voice,301
29,01,Alabama,Unwanted Calls,Wired,Prerecorded Voice,409
...,...,...,...,...,...,...
1774,56,Wyoming,Robocalls,Internet (VOIP),Autodialed Live Voice Call,1
1775,56,Wyoming,Robocalls,Internet (VOIP),Prerecorded Voice,6
1776,56,Wyoming,Robocalls,Wired,Abandoned Calls,3
1777,56,Wyoming,Robocalls,Wired,Autodialed Live Voice Call,5
1778,56,Wyoming,Robocalls,Wired,Prerecorded Voice,35
1779,56,Wyoming,Robocalls,Wireless (cell phone/other mobile device),Abandoned Calls,6
1780,56,Wyoming,Robocalls,Wireless (cell phone/other mobile device),Autodialed Live Voice Call,6
1781,56,Wyoming,Robocalls,Wireless (cell phone/other mobile device),Prerecorded Voice,67
1782,56,Wyoming,Robocalls,Wireless (cell phone/other mobile device),Text Message,1
1783,56,Wyoming,Telemarketing (including do not call and spoof...,Internet (VOIP),Abandoned Calls,2
1784,56,Wyoming,Telemarketing (including do not call and spoof...,Internet (VOIP),Live Voice,7
1785,56,Wyoming,Telemarketing (including do not call and spoof...,Internet (VOIP),Prerecorded Voice,6
1786,56,Wyoming,Telemarketing (including do not call and spoof...,Wired,Abandoned Calls,8
1787,56,Wyoming,Telemarketing (including do not call and spoof...,Wired,Live Voice,58
1788,56,Wyoming,Telemarketing (including do not call and spoof...,Wired,Prerecorded Voice,20
1789,56,Wyoming,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Abandoned Calls,10
1790,56,Wyoming,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Email,1
1791,56,Wyoming,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Live Voice,105
1792,56,Wyoming,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Prerecorded Voice,42
1793,56,Wyoming,Telemarketing (including do not call and spoof...,Wireless (cell phone/other mobile device),Text Message,9
1794,56,Wyoming,Unwanted Calls,Internet (VOIP),Abandoned Calls,4
1795,56,Wyoming,Unwanted Calls,Internet (VOIP),Live Voice,5
1796,56,Wyoming,Unwanted Calls,Internet (VOIP),Prerecorded Voice,19
1797,56,Wyoming,Unwanted Calls,Wired,Abandoned Calls,62
1798,56,Wyoming,Unwanted Calls,Wired,Live Voice,38
1799,56,Wyoming,Unwanted Calls,Wired,Prerecorded Voice,120
1800,56,Wyoming,Unwanted Calls,Wireless (cell phone/other mobile device),Abandoned Calls,64
1801,56,Wyoming,Unwanted Calls,Wireless (cell phone/other mobile device),Live Voice,119
1802,56,Wyoming,Unwanted Calls,Wireless (cell phone/other mobile device),Prerecorded Voice,220
1803,56,Wyoming,Unwanted Calls,Wireless (cell phone/other mobile device),Text Message,11

In [31]:
df_out = pd.merge(item_counts,state_data,left_on='state',right_on='State_Name',how='inner')

In [32]:
df_out.columns

Index(['id', 'state', 'issue', 'method', 'type', 'count', 'State_Name', 'Pop'], dtype='object')

In [33]:
keep_cols = ['id','state','issue','method','type','count','Pop']

In [34]:
df_out = df_out[keep_cols]

In [38]:
df_out.rename({'Pop':'population'},axis='columns').to_csv('viz/call_counts.csv',index=False)

In [42]:
df_out['count'] = df_out['count'].astype('int')
df_out.groupby(['id','state','Pop'])['count'].sum().reset_index().rename({'Pop':'population'},axis='columns').to_csv('viz/call_counts.csv',index=False)

In [46]:
tdf = df_out.groupby(['id','state','Pop'])['count'].sum().reset_index()

In [51]:
(tdf['count']/tdf['Pop'].astype(int)*100000).sort_values()

1     102.923907
24    109.391166
34    118.672187
11    120.873698
25    121.293695
18    125.107887
41    125.250075
14    131.323374
3     131.427671
45    146.575358
48    154.942431
40    158.709647
43    160.763184
0     161.010796
22    161.676045
32    163.870932
39    164.284059
16    166.202703
36    166.215285
49    166.593046
31    166.934870
19    168.185391
13    171.837866
12    172.100458
44    176.995070
33    179.821681
10    181.529972
26    182.998291
50    183.820666
42    184.534439
15    186.525017
23    186.930412
38    188.044719
9     190.456740
4     190.543044
35    191.514702
17    192.171609
27    194.581572
29    198.015714
7     201.101977
21    213.440770
30    217.611904
37    218.745593
2     222.877705
28    229.436408
47    230.479600
46    245.606641
6     268.483051
20    286.758376
5     296.564133
8     451.986248
dtype: float64